ui: mocha-bdd
browsers:
  - name: chrome
    version: '27..latest'
  - name: ie
    version: '9..latest'
  - name: safari
    version: '6..latest'
  - name: firefox
    version: '24..latest'
  - name: iphone
    version: '8.1..latest'
  - name: ipad
    version: '8.1..latest'
